### ISSUE TITLE
The final result

### ISSUE THREAD

**Issue by hillaric** [LZGMatrix/CDPN_ICCV2019_ZhigangLi#1]
Sorry to bother you, I use the stage3.checkpoint in your link, but I got the result below, I think the result is not correct.
![image](https://user-images.githubusercontent.com/50513602/112826289-5f7b4700-90bf-11eb-9909-8c999f760dc3.png)

**Comment by LZGMatrix** [comment]
@hillaric  Hi, this result is correct. For ADD metric, the thresholds (i.e. 0.02, 0.05, 0.10 here) are the ratio of the diameter of object. So, for ADD-0.1d, our accuracy is 91.36%. In short, you should pay attention to the last row of add performance.
